ALTER TABLE edge_nodes ADD COLUMN IF NOT EXISTS capabilities JSONB DEFAULT '[]';
ALTER TABLE edge_nodes ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(128);
ALTER TABLE edge_nodes ADD COLUMN IF NOT EXISTS center_sync VARCHAR(32);
ALTER TABLE edge_nodes ADD COLUMN IF NOT EXISTS disk_usage_mb FLOAT;
